
```{r}
library(Seurat)
library(Matrix)
```

```{r}
# Setting work directory so that reading data is relative to this notebook
wd <- setwd(".")
```

```{r}
# Reading in ADT object written to file by analysis notebook
ADT_seurat <- readRDS(paste(wd, "ADT_seurat_analysis_output/seurat_objects", "seurat.rds", sep="/"))
```

```{r}
ADT_mcl_table <- read.table(paste(wd, "ADT_mcl_work/mcl_seurat_table/ADT_srt_mcl.file", sep = "/"))
```

```{r}
ADT_mcl_len <- dim(ADT_mcl_table)[1]
```

```{r}
ADT_mcl_df <- as.data.frame(ADT_mcl_table$V2[2:ADT_mcl_len]) 
```

```{r}
rownames(ADT_mcl_df) <- ADT_mcl_table$V1[2:ADT_mcl_len]
colnames(ADT_mcl_df) <- "MCL_clustering"
```

```{r}
ADT_seurat@meta.data$MCL_clustering <- ADT_mcl_df$MCL_clustering
```

```{r}
DimPlot(ADT_seurat, reduction = "umap", label = ADT_seurat@meta.data$MCL_clustering)
```

```{r}
DimPlot(ADT_seurat, reduction = "umap", label = ADT_seurat@meta.data$seurat_clusters)
```

```{r}
# Reading in RNA object written to file by analysis notebook
RNA_seurat <- readRDS(paste(wd, "RNA_seurat_analysis_output/seurat_objects", "seurat.rds", sep="/"))
```

```{r}
RNA_mcl_table <- read.table(paste(wd, "RNA_mcl_work/mcl_seurat_table/RNA_srt_mcl.file", sep = "/"))
```

```{r}
RNA_mcl_len <- dim(RNA_mcl_table)[1]
```

```{r}
RNA_mcl_df <- as.data.frame(RNA_mcl_table$V2[2:RNA_mcl_len]) 
```

```{r}
rownames(RNA_mcl_df) <- RNA_mcl_table$V1[2:RNA_mcl_len]
colnames(RNA_mcl_df) <- "MCL_clustering"
```

```{r}
RNA_seurat@meta.data$MCL_clustering <- RNA_mcl_df$MCL_clustering
```

```{r}
DimPlot(RNA_seurat, reduction = "umap", label = RNA_seurat@meta.data$MCL_clustering)
```

```{r}
DimPlot(RNA_seurat, reduction = "umap", label = RNA_seurat@meta.data$seurat_clusters)
```