
### ADT DATA ###

```{r}
library(Seurat)
library(Matrix)
library(SeuratDisk)
library(SeuratObject)
library(dplyr)
```

```{r}
# Setting work directory so that reading data is relative to this notebook
wd <- setwd(".")
```

```{r}
# Reading in ADT object written to file by analysis notebook
ADT_seurat <- readRDS(paste(wd, "ADT_seurat_analysis_output/seurat_objects", "seurat.rds", sep="/"))
```

```{r}
#Removing duplicate clustering metadata generated for each clustering and default "seurat_clusters" column

ADT_seurat@meta.data <- ADT_seurat@meta.data %>% select(-contains(c("RNA_snn_res", "seurat_clusters")))
```

### ADDING CELL TYPE ANNOTATION FROM REFERENCE DATASET

```{r}
#Get list of barcodes needed for subsetting later
ADT_barcodes <- colnames(ADT_seurat)
```

```{r}
#Load in reference seurat object containing cell type annotation data
ref_srat <- LoadH5Seurat(paste(wd, "data/pbmc_multimodal.h5seurat", sep="/"))
```

```{r}
#extract cell type annotation data into a dataframe
celltype_df <- as.data.frame(ref_srat@meta.data[,c("celltype.l1", "celltype.l2", "celltype.l3")])
```

```{r}
#rename rows to be the cell barcodes and rename column to be appropriat
rownames(celltype_df) <- rownames(ref_srat@meta.data)
colnames(celltype_df) <- c("celltype_level_1","celltype_level_2","celltype_level_3")
```

```{r}
#filter celltype dataframe to only contain cells remaining from preprocessing in seurat object as reference seurat was not preprocessed
ADT_filt_celltype_df <- subset(celltype_df, rownames(celltype_df) %in% ADT_barcodes)
```

```{r}
#add cell type annotations to seurat
ADT_seurat@meta.data$celltype_level_1 <- ADT_filt_celltype_df$celltype_level_1
ADT_seurat@meta.data$celltype_level_2 <- ADT_filt_celltype_df$celltype_level_2
ADT_seurat@meta.data$celltype_level_3 <- ADT_filt_celltype_df$celltype_level_3
```

### Integrating MCL clustering data into Seurat

```{r}
# Add each MCL clustering to seurat object metadata
for (infl in seq(from = 110, to = 400, by=10)) {
  mcl_file <- paste("I", infl, "_srt_mcl.file", sep = "")
  mcl_table <- read.table(paste(wd, "/ADT_mcl_work/mcl_seurat_table/", mcl_file, sep = ""))
  mcl_len <- dim(mcl_table)[1]
  ADT_seurat@meta.data[paste("mcl_I", infl, sep = "")] <- mcl_table$V2[2:mcl_len]
} 
```

### ADDING VOLATILITY

```{r}
#Read volatility table
ADT_vol_table <- read.table(paste(wd, "ADT_mcl_work/comparison/vol.srt.file", sep = "/"))
```

```{r}
#calculate length of table
ADT_vol_len <- dim(ADT_vol_table)[1]
```

```{r}
#create dataframe containing only volatility scores and remove dummy line that MCL needs
ADT_vol_df <- as.data.frame(ADT_vol_table$V3[2:ADT_vol_len])
```

```{r}
#rename rows to be the cell barcodes and rename column to be appropriate
rownames(ADT_vol_df) <- ADT_vol_table$V2[2:ADT_vol_len]
colnames(ADT_vol_df) <- "Volatility"
```

```{r}
#Integrate volatility scores into seurat object
ADT_seurat@meta.data$Volatility <- ADT_vol_df$Volatility
```

```{r}
# Saving the seurat object so it can easily be read in for future analysis
dir.create(file.path(wd, "ADT_seurat_analysis_output", "integrated_seurat"), recursive = TRUE)
saveRDS(ADT_seurat, paste(wd, "ADT_seurat_analysis_output/integrated_seurat", "full_seurat.rds", sep="/"))
```

### RNA DATA ###

```{r}
# Reading in ADT object written to file by analysis notebook
RNA_seurat <- readRDS(paste(wd, "RNA_seurat_analysis_output/seurat_objects", "seurat.rds", sep="/"))
```

```{r}
#Removing duplicate clustering metadata generated for each clustering and default "seurat_clusters" column

RNA_seurat@meta.data <- RNA_seurat@meta.data %>% select(-contains(c("RNA_snn_res", "seurat_clusters")))
```

### ADDING CELL TYPE ANNOTATION FROM REFERENCE DATASET

```{r}
#Get list of barcodes needed for subsetting later
RNA_barcodes <- colnames(RNA_seurat)
```

```{r}
#filter celltype dataframe to only contain cells remaining from preprocessing in seurat object as reference seurat was not preprocessed
RNA_filt_celltype_df <- subset(celltype_df, rownames(celltype_df) %in% RNA_barcodes)
```

```{r}
#add cell type annotations to seurat
RNA_seurat@meta.data$celltype_level_1 <- RNA_filt_celltype_df$celltype_level_1
RNA_seurat@meta.data$celltype_level_2 <- RNA_filt_celltype_df$celltype_level_2
RNA_seurat@meta.data$celltype_level_3 <- RNA_filt_celltype_df$celltype_level_3
```

### Integrating MCL clustering data into Seurat

```{r}
# Add each MCL clustering to seurat object metadata
for (infl in seq(from = 110, to = 400, by=10)) {
  mcl_file <- paste("I", infl, "_srt_mcl.file", sep = "")
  mcl_table <- read.table(paste(wd, "/RNA_mcl_work/mcl_seurat_table/", mcl_file, sep = ""))
  mcl_len <- dim(mcl_table)[1]
  RNA_seurat@meta.data[paste("mcl_I", infl, sep = "")] <- mcl_table$V2[2:mcl_len]
} 
```

### ADDING VOLATILITY

```{r}
#Read volatility table
RNA_vol_table <- read.table(paste(wd, "RNA_mcl_work/comparison/vol.srt.file", sep = "/"))
```

```{r}
#calculate length of table
RNA_vol_len <- dim(RNA_vol_table)[1]
```

```{r}
#create dataframe containing only volatility scores and remove dummy line that MCL needs
RNA_vol_df <- as.data.frame(RNA_vol_table$V3[2:RNA_vol_len])
```

```{r}
#rename rows to be the cell barcodes and rename column to be appropriate
rownames(RNA_vol_df) <- RNA_vol_table$V2[2:RNA_vol_len]
colnames(RNA_vol_df) <- "Volatility"
```

```{r}
#Integrate volatility scores into seurat object
RNA_seurat@meta.data$Volatility <- RNA_vol_df$Volatility
```

```{r}
# Saving the seurat object so it can easily be read in for future analysis
dir.create(file.path(wd, "RNA_seurat_analysis_output", "integrated_seurat"), recursive = TRUE)
saveRDS(RNA_seurat, paste(wd, "RNA_seurat_analysis_output/integrated_seurat", "full_seurat.rds", sep="/"))
```

```{r}
# Saving the environment so entire notebook can be loaded back up quickly
save.image(paste(wd, "integrated.rdata", sep="/"))
```