
```{r}
library(Seurat)
library(Matrix)
```

# Seurat tutorial: https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

```{r}
# Setting work directory so that reading data is relative to this notebook
wd <- setwd(".")
```

```{r}
# Data should be generated into a subdirectory called data by get-data.sh, each type of data is stored within a subdirectory of data
RNA_data <- Read10X(paste(wd, "data/RNA", sep="/"))
```

```{r}
# Chosen to filter using notebook guidance of 3 cells and 200 features to remove empty cells and non-signficant genes
RNA_seurat <- CreateSeuratObject(RNA_data, project = "pbmc-RNA", min.cells = 3, min.features = 200)
```

```{r}
# Calcualte mitochondrial rna percentage in each cell
RNA_seurat[["percent.mt"]] <- PercentageFeatureSet(RNA_seurat, pattern = "^MT-")
```

```{r}
# Removing cells that are high in mitochondrial RNA as those cells are likely lysed and dead
# Removing genes present in too many cells as those won't be potential marker genes
# Removing genes not present in enough cells as those won't be marker genes for a cell type (this is a risk as sometimes very rare cell types only have a few cells collected so could be losing information here, it is done for reducing size of object)
RNA_seurat <- subset(RNA_seurat, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
```

```{r}
# Normalising gex expression data so that the expression of genes between cells can be adequately compared, using default method and scaling factor, number of genes is set to 2000 for calculation.
RNA_seurat <- NormalizeData(RNA_seurat)
```

```{r}
# To find the genes that are highly variable in their expression between cells, FindVariableFeatures is used. Default is to use a selection method that fits variance and mean relationship using local regression
RNA_seurat <- FindVariableFeatures(RNA_seurat)
```

```{r}
# In a seurat object, the row names are the genes and the column names are the cells. Scaling the data makes each expression value larger for comparison while removing the dominance of highly expressed genes. Scaling data requires a list of genes. 
genes <- rownames(RNA_seurat)
RNA_seurat <- ScaleData(RNA_seurat, features = genes)
```

```{r}
# Saving genes list to file
dir.create(file.path(wd, "RNA_seurat_analysis_output", "gene_files"), recursive = TRUE)
write.table(genes, file="RNA_seurat_analysis_output/gene_files/filtered_features.txt", row.names=FALSE, col.names=FALSE, sep="\t", quote = FALSE)
```

```{r}
# Dimensionality reduction reduces the high levels of variability between cells into comparative vectorised space where each cells position in space is representative of its values across all variables
RNA_seurat <- RunPCA(RNA_seurat, features = VariableFeatures(object = RNA_seurat))
```

```{r}
# Dimensionality reduction combines as much variance as possible into principal components. Each principal component in turn should contain the maximum possible variance it can. An elbow plot visualises how much variance each principal component contains.
ElbowPlot(RNA_seurat)
```

# Looking at this graph, the sudden drop in standard deviation comes in the 4th principal component. This shows that the first 4 dimensions in reduced space contain most of the variance and should be used to build the nearest neighbour graph

```{r}
# Before clustering can be ran, a nearest neighbour graph needs to be built for the clustering to work on. This connects each cell together in a network. The first four dimensions are being used to build the neighbourhood graph after inspecting elbow plot.
RNA_seurat <- FindNeighbors(RNA_seurat, dims = 1:4)
```

```{r}
# Matrix market files are a filetype type that stores a nearest neighbour graph as a matrix. This needs to be extracted from the seurat object to be used as the input for MCL
nn_matrix <- as(RNA_seurat@graphs$RNA_snn, "dgCMatrix")
```

```{r}
# Need to create a directory for matrix market file to be saved to
dir.create(file.path(wd, "RNA_seurat_analysis_output", "nn_matrix"), recursive = TRUE)
```

```{r}
# Writing matrix market file to system for MCL analysis
writeMM(nn_matrix, paste(wd, "RNA_seurat_analysis_output/nn_matrix", "nn.mtx", sep="/"))
```

```{r}
# Clustering data by default seurat uses Louvain so have to specify Leiden which is algorithm 4, using resolution values of 0.1-2.0 which are used to gauge how fine or coarse the clusters should be

dir.create(file.path(wd, "RNA_seurat_analysis_output", "cls_lei"), recursive = TRUE)

# Have to use igraph method on ADT data so will also use it here
res_ls <- c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0)
for (res in res_ls) {
    outfile = sprintf("lei_r%03d", 10* res)
    RNA_seurat <- FindClusters(RNA_seurat, resolution = res, algorithm = 4, method = "igraph")
    write.table(RNA_seurat@active.ident, file=paste(wd, "RNA_seurat_analysis_output/cls_lei", outfile, sep = "/"), row.names=TRUE, col.names=FALSE, sep="\t", quote = FALSE)
    RNA_seurat[[outfile]] <- RNA_seurat[["seurat_clusters"]]
    write.table(RNA_seurat@meta.data[[outfile]], file=paste(wd, "/RNA_seurat_analysis_output/cls_lei/", outfile, ".table", sep = ""), row.names=FALSE, col.names=FALSE, sep="\t", quote = FALSE)
}
```

```{r}
#Saving leiden clustering to file for later comparison with MCL
dir.create(file.path(wd, "RNA_seurat_analysis_output", "cls_lei"), recursive = TRUE)
write.table(RNA_seurat@active.ident, file="RNA_seurat_analysis_output/cls_lei/lei_r08", row.names=TRUE, col.names=FALSE, sep="\t", quote = FALSE)
```

```{r}
# After clustering the data, it needs to be embedded. This can be done with multiple dimensionality reduction algorithms, UMAP is preferred because it is non-linear dimensional reduction method so it does not take each principal component in an order where each component's max variation is based on the variation already factored in by the previous principal component. UMAP can only be run after PCA.
RNA_seurat <- RunUMAP(RNA_seurat, dims = 1:4)
```

```{r}
# Visualisation of the clustering
DimPlot(RNA_seurat, reduction = "umap")
```

```{r}
# Saving barcodes to file
barcodes <- colnames(RNA_seurat)
dir.create(file.path(wd, "RNA_seurat_analysis_output", "barcode_files"), recursive = TRUE)
write.table(barcodes, file="RNA_seurat_analysis_output/barcode_files/filtered_barcodes.txt", row.names=FALSE, col.names=FALSE, sep="\t", quote = FALSE)
```

```{r}
# Saving the seurat object so it can easily be read in for future analysis
dir.create(file.path(wd, "RNA_seurat_analysis_output", "seurat_objects"), recursive = TRUE)
saveRDS(RNA_seurat, paste(wd, "RNA_seurat_analysis_output/seurat_objects", "seurat.rds", sep="/"))
```

```{r}
# Saving the environment so entire notebook can be loaded back up quickly
save.image(paste(wd, "RNA_seurat_analysis_output/seurat_objects", "seurat.rdata", sep="/"))
```

